#!/bin/sh
[ "$(board_name)" = "comfast,cf-wa350" ] || exit 0

uci -q batch <<EOF
# --- التكوين الجديد (25.12) ---
delete wireless.default_radio0.disabled
delete wireless.default_radio1.disabled
set wireless.default_radio0.ssid='WA350-RESCUE-5G'
set wireless.default_radio0.encryption='none'
set wireless.default_radio1.ssid='WA350-RESCUE'
set wireless.default_radio1.encryption='none'

# --- التكوين القديم (24.10) كاحتياط ---
delete wireless.radio0.disabled
delete wireless.radio1.disabled

# --- الشبكة ---
set network.lan.proto='static'
set network.lan.ipaddr='192.168.1.1'
set network.lan.netmask='255.255.255.0'


# dnsmasq: DNS forwarder only (the upstream gateway does not serve DNS here)
uci set dhcp.@dnsmasq[0].noresolv='1'
uci -q delete dhcp.@dnsmasq[0].server
uci add_list dhcp.@dnsmasq[0].server='8.8.8.8'
uci add_list dhcp.@dnsmasq[0].server='1.1.1.1'

#uci -q delete system.@button[0]
uci commit system
uci commit dhcp

EOF

uci -q commit wireless
uci -q commit network

logger -t rescue-wifi "WA350 rescue WiFi enabled (diagnostic build)"
exit 0
